#Archivo KV Principal

#:import WindowManager kivy.uix.screenmanager.ScreenManager

WindowManager:
    MenuScreen:
    AreasScreen:
    SalonesScreen:
    EstadisticaScreen:
    DonacionesScreen:
    DistribucionScreen:
    LogisticaScreen:
    OtrasAreasScreen:
    EnsenanzaScreen:
    RecepcionScreen:
    ReporteScreen:
    AyudaScreen:

<AreasScreen>:
    name: "areas"
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "Pantalla de Áreas"
        Button:
            text: "Volver"
            on_press: root.manager.current = "menu"

<SalonesScreen>:
    name: "salones"
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "Pantalla de Salones"
        Button:
            text: "Volver"
            on_press: root.manager.current = "menu"

<EstadisticaScreen>:
    name: "estadistica"
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "Pantalla de Estadística"
        Button:
            text: "Volver"
            on_press: root.manager.current = "menu"

<DonacionesScreen>:
    name: "donaciones"
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "Pantalla de Donaciones"
        Button:
            text: "Volver"
            on_press: root.manager.current = "menu"

<DistribucionScreen>:
    name: "distribucion"
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "Pantalla de Distribución"
        Button:
            text: "Volver"
            on_press: root.manager.current = "menu"

<LogisticaScreen>:
    name: "logistica"
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "Pantalla de Logística"
        Button:
            text: "Volver"
            on_press: root.manager.current = "menu"

<OtrasAreasScreen>:
    name: "otras_areas"
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "Pantalla de Otras Áreas"
        Button:
            text: "Volver"
            on_press: root.manager.current = "menu"

<EnsenanzaScreen>:
    name: "ensenanza"
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "Pantalla de Enseñanza"
        Button:
            text: "Volver"
            on_press: root.manager.current = "menu"

<RecepcionScreen>:
    name: "recepcion"
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "Pantalla de Recepción"
        Button:
            text: "Volver"
            on_press: root.manager.current = "menu"

<ReporteScreen>:
    name: "reporte"
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "Pantalla de Reporte"
        Button:
            text: "Volver"
            on_press: root.manager.current = "menu"

<AyudaScreen>:
    name: "ayuda"
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "Pantalla de Ayuda"
        Button:
            text: "Volver"
            on_press: root.manager.current = "menu"