<AyudaScreen>:
    name: 'ayuda'
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: 0.102, 0.2, 0.396, 1
            Rectangle:
                pos: self.pos
                size: self.size
        ScrollView:
            Label:
                text: 'Ayuda de Maranatha Infantil'
                font_size: 30
                color: 1, 1, 1, 1
                size_hint_y: None
                height: 50
    # Botón Volver al Menú
    Button:
        text: 'Volver al Menú'
        font_size: 28
        background_normal: ''
        background_color: (0, 119/255, 194/255, 1)
        size_hint_y: None
        height: 50
        on_press: root.manager.current = 'menu'
