<DonacionesScreen>:
    name: 'donaciones'
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: 0.102, 0.2, 0.396, 1
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            text: 'Donaciones de Maranatha Infantil'
            font_size: 36
            color: 1, 1, 1, 1
            size_hint_y: None
            height: 50
        # Formulario
        ScrollView:
            size_hint_y: 1  # Ocupa todo el espacio vertical disponible
            GridLayout:
                cols: 2
                padding: 20
                spacing: 20
                size_hint_y: None
                height: self.minimum_height
                row_default_height: 50
                Label:
                    text: 'Id Donación:'
                    font_size: 20
                    color: 1, 1, 1, 1
                    size_hint_y: None
                    height: 30
                TextInput:
                    id: donacion_id
                Label:
                    text: 'Descripción:'
                    font_size: 20
                    color: 1, 1, 1, 1
                    size_hint_y: None
                    height: 30
                TextInput:
                    id: donacion_descripcion
                Label:
                    text: 'Cantidad:'
                    font_size: 20
                    color: 1, 1, 1, 1
                    size_hint_y: None
                    height: 30
                TextInput:
                    id: donacion_cantidad
                Label:
                    text: 'Unidad:'
                    font_size: 20
                    color: 1, 1, 1, 1
                    size_hint_y: None
                    height: 30
                TextInput:
                    id: donacion_unidad
                Label:
                    text: 'Fecha (YYYY-MM-DD):'
                    font_size: 20
                    color: 1, 1, 1, 1
                    size_hint_y: None
                    height: 30
                BoxLayout:
                    orientation: 'horizontal'
                    spacing: 10
                    TextInput:
                        id: donacion_fecha
                        readonly: True
                        hint_text: 'YYYY-MM-DD'
                    Button:
                        size_hint_x: None
                        width: 50
                        background_normal: ''
                        background_color: (0, 119/255, 194/255, 1)
                        on_press: root.abrir_datepicker('donacion_fecha')
                        Image:
                            source: 'images/calendar_icon.png'
                            center_x: self.parent.center_x
                            center_y: self.parent.center_y
                            size: 30, 30
                            allow_stretch: True
                Label:
                    text: 'Equipo:'
                    font_size: 20
                    color: 1, 1, 1, 1
                    size_hint_y: None
                    height: 30
                TextInput:
                    id: donacion_equipo
        # Contenedor de Botones
        BoxLayout:
            size_hint_y: None
            height: 50
            spacing: 10
            padding: 10
            Button:
                text: 'Crear'
                font_size: 28
                background_normal: ''
                background_color: (0, 119/255, 194/255, 1)
                size_hint_y: None
                height: 50
                on_press: root.crear_donacion()
            Button:
                text: 'Actualizar'
                font_size: 28
                background_normal: ''
                background_color: (0, 119/255, 194/255, 1)
                size_hint_y: None
                height: 50
                on_press: root.actualizar_donacion()
            Button:
                text: 'Eliminar'
                font_size: 28
                background_normal: ''
                background_color: (0, 119/255, 194/255, 1)
                size_hint_y: None
                height: 50
                on_press: root.eliminar_donacion(donacion_id.text)
            Button:
                text: 'Listar'
                font_size: 28
                background_normal: ''
                background_color: (0, 119/255, 194/255, 1)
                size_hint_y: None
                height: 50
                on_press: root.manager.current = 'lista_donaciones'
            Button:
                text: 'Buscar'
                font_size: 28
                background_normal: ''
                background_color: (0, 119/255, 194/255, 1)
                size_hint_y: None
                height: 50
                on_press: 
                    root.buscar_donacion()
                    donacion_id.text = ''
                    donacion_descripcion.text = ''
        # Botón Inicio
        Button:
            text: 'Volver al Menú'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = 'menu'