<EstadisticaScreen>:
    name: 'estadistica'
    Label:
        text: 'Vista de Estadistica'
        font_size: 32
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    Button:
        text: 'Volver al Menú'
        font_size: 28
        background_normal: ''
        background_color: (0, 119/255, 194/255, 1)
        size_hint_y: None
        height: 50
        on_press: root.manager.current = 'menu'
