<ListAreasScreen>:
    name: 'lista_areas'
    
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: 0.102, 0.2, 0.396, 1
            Rectangle:
                pos: self.pos
                size: self.size

        # 1. TÍTULO (Fijo arriba)
        Label:
            text: 'Lista de Áreas'
            font_size: '22sp'
            size_hint_y: None
            height: dp(60)
            bold: True

        # 2. ÁREA DE LA LISTA (Scrollable)
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            
            GridLayout:
                id: lista_areas
                cols: 2  # Mantenemos 2 columnas, pero con mayor altura de fila
                size_hint_y: None
                height: self.minimum_height
                spacing: dp(5)
                padding: [dp(10), dp(10), dp(10), dp(10)]
                row_default_height: dp(50) # Altura de fila más cómoda para el dedo
                row_force_default: True

        # 3. FOOTER DE BOTONES (Fijo abajo)
        GridLayout:
            cols: 2
            size_hint_y: None
            height: dp(120)
            padding: dp(10)
            spacing: dp(10)

            Button: 
                text: 'Actualizar'
                font_size: '16sp'
                bold: True
                background_normal: ''
                background_color: (0, 0.47, 0.76, 1) # Azul
                on_press: root.controlador.listar_areas(root)
                
            Button:
                text: 'Cerrar'
                font_size: '16sp'
                background_normal: ''
                background_color: (0.5, 0.5, 0.5, 1) # Gris
                on_press: app.root.current = 'areas'