<ListSalonesScreen>:
    name: 'lista_salones'
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: 0.102, 0.2, 0.396, 1
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            text: 'Lista de Salones'
            font_size: '22sp'
            bold: True
            color: 1, 1, 1, 1
            size_hint_y: None
            height: dp(60)
        ScrollView:
            do_scroll_x: False
            GridLayout:
                id: lista_salones
                cols: 1 # Optimizado para móvil: una columna
                size_hint_y: None
                height: self.minimum_height
                spacing: dp(10)
                padding: dp(15)

        #Contenedor de botones
        BoxLayout:
            orientation: 'vertical'
            spacing: dp(10)
            padding: dp(10)
            size_hint_y: None
            height: self.minimum_height
            GridLayout:
                cols: 2
                spacing: dp(10)
                size_hint_y: None
                height: dp(70)
                
                Button:
                    text: 'LISTAR'
                    font_size: '18sp'
                    bold: True
                    background_normal: ''
                    background_color: (0, 0.6, 0.2, 1)
                    on_press: root.controlador.listar_salones(root)
                Button:
                    text: 'VOLVER'
                    font_size: '18sp'
                    bold: True
                    background_normal: ''
                    background_color: (0.5, 0.5, 0.5, 1)
                    on_press: root.manager.current = 'salones'