<ListDistribucionesScreen>:
    name: 'lista_distribuciones'

    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: 0.102, 0.2, 0.396, 1
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            text: 'Lista de Distribuciones'
            font_size: '22sp'
            size_hint_y: None
            height: dp(60)
            bold: True

        ScrollView:
            do_scroll_x: False
            do_scroll_y: True

            GridLayout:
                id: lista_distribuciones
                cols: 7
                size_hint_y: None
                height: self.minimum_height
                row_default_height: dp(50)
                row_force_default: True
                spacing: [0, dp(5)]
                padding: [dp(10), dp(5)]

        GridLayout:
            cols: 2
            spacing: dp(10)
            padding: dp(10)
            size_hint_y: None
            height: dp(70)

            Button:
                text: 'LISTAR'
                font_size: '16sp'
                bold: True
                background_normal: ''
                background_color: (0, 0.47, 0.76, 1)
                on_press: root.cargar_distribuciones()

            Button:
                text: 'CERRAR'
                font_size: '16sp'
                background_normal: ''
                background_color: (0.5, 0.5, 0.5, 1)
                on_press: app.root.current = 'distribuciones'
