<LogisticaScreen>:
    name: 'logisticas'
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: 0.102, 0.2, 0.396, 1
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            text: 'Logistica de Maranatha Infantil'
            font_size: '22sp'
            bold: True
            color: 1, 1, 1, 1
            size_hint_y: None
            height: dp(60)
        # Formulario
        ScrollView:
            do_scroll_x: False
            GridLayout:
                cols: 2
                padding: dp(15)
                spacing: dp(12)
                size_hint_y: None
                height: self.minimum_height
                row_default_height: dp(45)
                cols: 2 # Asegura que el formulario tenga 2 columnas

                Label:
                    text: 'Almacén:'
                    font_size: '16sp'
                    halign: 'left'
                    text_size: self.size
                TextInput:
                    text: root.logistica_almacen_text
                    id: logistica_almacen
                    multiline: False

                Label:
                    text: 'Capitán:'
                    font_size: '16sp'
                    halign: 'left'
                    text_size: self.size
                TextInput:
                    text: root.logistica_capitan_text
                    id: logistica_capitan
                    multiline: False

                Label:
                    text: 'Distribución:'
                    font_size: '16sp'
                    halign: 'left'
                    text_size: self.size
                TextInput:
                    text: root.logistica_distribucion_text
                    id: logistica_distribucion
                    multiline: False

                Label:
                    text: 'Hidratación:'
                    font_size: '16sp'
                    halign: 'left'
                    text_size: self.size
                TextInput:
                    text: root.logistica_hidratacion_text
                    id: logistica_hidratacion
                    multiline: False

                Label:
                    text: 'Pasillo:'
                    font_size: '16sp'
                    halign: 'left'
                    text_size: self.size
                TextInput:
                    text: root.logistica_pasillo_text
                    id: logistica_pasillo
                    multiline: False

                Label:
                    text: 'Secretaría:'
                    font_size: '16sp'
                    halign: 'left'
                    text_size: self.size
                TextInput:
                    text: root.logistica_secretaria_text
                    id: logistica_secretaria
                    multiline: False

                Label:
                    text: 'Fecha:'
                    font_size: '16sp'
                    halign: 'left'
                    text_size: self.size
                BoxLayout:
                    orientation: 'horizontal'
                    spacing: dp(5)
                    TextInput:
                        id: logistica_fecha
                        text: root.logistica_fecha_text
                        readonly: True
                        hint_text: 'YYYY-MM-DD'
                    Button:
                        size_hint_x: None
                        width: dp(50)
                        background_normal: ''
                        background_color: (0, 119/255, 194/255, 1)
                        on_press: root.abrir_datepicker('logistica_fecha')
                        Image:
                            source: 'images/calendar_icon.png'
                            pos: self.parent.pos
                            size: self.parent.size
                            allow_stretch: True

                Label:
                    text: 'ID Logística (Busq):'
                    font_size: '16sp'
                TextInput:
                    text: root.logistica_id_text
                    id: logistica_id
                    multiline: False
                    hint_text: 'ID para buscar/borrar'
        #Contenedor de botones (Acciones principales)
        GridLayout:
            cols: 2
            size_hint_y: None
            height: dp(120)
            spacing: dp(10)
            padding: dp(10)
            
            Button:
                text: 'CREAR'
                font_size: '18sp'
                bold: True
                background_normal: ''
                background_color: (0, 0.47, 0.76, 1) # Azul
                on_press: root.crear_logistica()
            Button:
                text: 'ACTUALIZAR'
                font_size: '18sp'
                bold: True
                background_normal: ''
                background_color: (0.1, 0.5, 0.7, 1) # Azul más claro
                on_press: root.actualizar_logistica()
            Button:
                text: 'ELIMINAR'
                font_size: '18sp'
                bold: True
                background_normal: ''
                background_color: (0.8, 0, 0, 1) # Rojo
                on_press: root.eliminar_logistica(logistica_id.text)
            Button:
                text: 'VER LISTA'
                font_size: '18sp'
                bold: True
                background_normal: ''
                background_color: (0, 0.6, 0.2, 1)
                on_press: root.ir_a_lista_logisticas()
        
        Button:
            text: 'VOLVER AL MENÚ'
            font_size: '18sp'
            bold: True
            background_normal: ''
            background_color: (0.4, 0.4, 0.4, 1)
            size_hint_y: None
            height: dp(50)
            on_press: root.manager.current = 'menu'
