<MenuScreen>:
    GridLayout:
        cols: 4
        rows: 6
        size: root.width, root.height
        padding: 10
        spacing: 10
        canvas.before:
            Color:
                rgba: 0.102, 0.2, 0.396, 1
            Rectangle:
                pos: self.pos
                size: self.size

        # Fila 1: Imágenes
        Image:
            source: 'images/areas.png'
        Image:
            source: 'images/salones.png'
        Image:
            source: 'images/aulas.png'
        Image:
            source: 'images/donacion.png'

        # Fila 2: Botones
        Button:
            text: 'AREAS'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "areas" # Agregado para navegación
        Button:
            text: 'SALONES'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "salones" # Agregado para navegación
        Button:
            text: 'ESTADISTICA'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "estadistica" # Agregado para navegación
        Button:
            text: 'DONACIONES'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "donaciones" # Agregado para navegación

        # Fila 3: Imágenes
        Image:
            source: 'images/distribucion.png'
        Image:
            source: 'images/logistic.png'
        Image:
            source: 'images/otras.png'
        Image:
            source: 'images/ensenanza.png'

        # Fila 4: Botones
        Button:
            text: 'DISTRIBUCION'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "distribucion" # Agregado para navegación
        Button:
            text: 'LOGISTICA'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "logistica" # Agregado para navegación
        Button:
            text: 'OTRAS AREAS'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "otras_areas" # Agregado para navegación
        Button:
            text: 'ENSEÑANZA'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "ensenanza" # Agregado para navegación

        # Fila 5: Imágenes
        Image:
            source: 'images/recepcion.png'
        Image:
            source: 'images/report.png'
        Image:
            source: 'images/ayuda.png'
        Image:
            source: 'images/exit.png'

        # Fila 6: Botones
        Button:
            text: 'RECEPCION'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "recepcion" # Agregado para navegación
        Button:
            text: 'REPORTE'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "reporte" # Agregado para navegación
        Button:
            text: 'AYUDA'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "ayuda" # Agregado para navegación
        Button:
            text: 'SALIR'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: app.stop() # Agregado para navegación