<MenuScreen>:
    GridLayout:
        cols: 4
        rows: 8
        size: root.width, root.height
        padding: 10
        spacing: 10
        canvas.before:
            Color:
                rgba: 0.102, 0.2, 0.396, 1
            Rectangle:
                pos: self.pos
                size: self.size

        # Fila 1: Imágenes
        Image:
            source: 'images/areas.png'
        Image:
            source: 'images/salones.png'
        Image:
            source: 'images/aulas.png'
        Image:
            source: 'images/donacion.png'

        # Fila 2: Botones
        Button:
            text: 'AREAS'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "areas"
        Button:
            text: 'SALONES'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "salones"
        Button:
            text: 'ESTADISTICA'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "estadistica"
        Button:
            text: 'DONACIONES'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "donaciones"

        # Fila 3: Imágenes
        Image:
            source: 'images/distribucion.png'
        Image:
            source: 'images/logistic.png'
        Image:
            source: 'images/otras.png'
        Image:
            source: 'images/ensenanza.png'

        # Fila 4: Botones
        Button:
            text: 'DISTRIBUCION'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "distribuciones"
        Button:
            text: 'LOGISTICA'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "logistica"
        Button:
            text: 'OTRAS AREAS'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "otrasareas"
        Button:
            text: 'ENSEÑANZA'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "ensenanza"

        # Fila 5: Imágenes
        Image:
            source: 'images/recepcion.png'
        Image:
            source: 'images/report.png'
        Image:
            source: 'images/ayuda.png'
        Image:
            source: 'images/combinar.png'

        # Fila 6: Botones
        Button:
            text: 'RECEPCION'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "recepcion"
        Button:
            text: 'REPORTE'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "reporte"
        Button:
            text: 'AYUDA'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "ayuda"
        Button:
            text: 'COMBINAR'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = "combinar_donaciones"

        # Fila 7: Imagen de Salir
        Image:
            source: 'images/exit.png'
        Widget: # Spacers
        Widget:
        Widget:

        # Fila 8: Botón Salir
        Button:
            text: 'SALIR'
            font_size: 28
            background_normal: ''
            background_color: (180/255, 0, 0, 1) # Rojo para salir
            size_hint_y: None
            height: 50
            on_press: app.stop()
        Widget:
        Widget:
        Widget: