<OtrasAreasScreen>:
    name: 'otrasareas'
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: 0.102, 0.2, 0.396, 1
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            text: 'Otras Áreas de Maranatha Infantil'
            font_size: 30
            color: 1, 1, 1, 1
            size_hint_y: None
            height: 50
        # Formulario
        ScrollView:
            size_hint_y: 1
            GridLayout:
                cols: 2
                padding: 20
                spacing: 20
                size_hint_y: None
                height: self.minimum_height
                row_default_height: 30
                Label:
                    text: 'Alabanza:'
                    font_size: 20
                    color: 1, 1, 1, 1
                    size_hint_y: None
                    height: 30
                TextInput:
                    id: otrasareas_alabanza
                Label:
                    text: 'Protocolo:'
                    font_size: 20
                    color: 1, 1, 1, 1
                    size_hint_y: None
                    height: 30
                TextInput:
                    id: otrasareas_protocolo
                Label:
                    text: 'Semillitas:'
                    font_size: 20
                    color: 1, 1, 1, 1
                    size_hint_y: None
                    height: 30
                TextInput:
                    id: otrasareas_semillitas
                Label:
                    text: 'Sonido:'
                    font_size: 20
                    color: 1, 1, 1, 1
                    size_hint_y: None
                    height: 30
                TextInput:
                    id: otrasareas_sonido
                Label:
                    text: 'Teatro:'
                    font_size: 20
                    color: 1, 1, 1, 1
                    size_hint_y: None
                    height: 30
                TextInput:
                    id: otrasareas_teatro
                Label:
                    text: 'TV:'
                    font_size: 20
                    color: 1, 1, 1, 1
                    size_hint_y: None
                    height: 30
                TextInput:
                    id: otrasareas_tv
                Label:
                    text: 'Ujier:'
                    font_size: 20
                    color: 1, 1, 1, 1
                    size_hint_y: None
                    height: 30
                TextInput:
                    id: otrasareas_ujier
                Label:
                    text: 'Fecha (YYYY-MM-DD):'
                    font_size: 20
                    color: 1, 1, 1, 1
                    size_hint_y: None
                    height: 30
                TextInput:
                    id: otrasareas_fecha
                Label:
                    text: 'ID Otras Áreas:'
                    font_size: 20
                    color: 1, 1, 1, 1
                    size_hint_y: None
                    height: 30
                TextInput:
                    id: otrasareas_id
                # Lista de otras áreas
                Label:
                    text: 'Lista de Otras Áreas:'
                    font_size: 20
                    color: 1, 1, 1, 1
                    size_hint_y: None
                    height: 30
                ScrollView:
                    GridLayout:
                        id: lista_otrasareas
                        cols: 3 # Nombre, Editar, Eliminar
                        size_hint_y: None
                        height: self.minimum_height
        BoxLayout:
            size_hint_y: None
            height: 50
            spacing: 10
            padding: 10        
            Button:
                text: 'Crear'
                font_size: 28
                background_normal: ''
                background_color: (0, 119/255, 194/255, 1)
                size_hint_y: None
                height: 50
                on_press: root.crear_otrasareas()
            Button:
                text: 'Actualizar'
                font_size: 28
                background_normal: ''
                background_color: (0, 119/255, 194/255, 1)
                size_hint_y: None
                height: 50
                on_press: root.actualizar_otrasareas()
            Button:
                text: 'Eliminar'
                font_size: 28
                background_normal: ''
                background_color: (0, 119/255, 194/255, 1)
                size_hint_y: None
                height: 50
                on_press: root.eliminar_otrasareas(otrasareas_id.text)
            Button:
                text: 'Listar'
                font_size: 28
                background_normal: ''
                background_color: (0, 119/255, 194/255, 1)
                size_hint_y: None
                height: 50
                on_press: root.cargar_otrasareas()
        Button:
            text: 'Volver al Menú'
            font_size: 28
            background_normal: ''
            background_color: (0, 119/255, 194/255, 1)
            size_hint_y: None
            height: 50
            on_press: root.manager.current = 'menu'
