<StyledPopup>:
    orientation: 'vertical'
    padding: 20
    spacing: 20
    canvas.before:
        Color:
            rgba: 0.102, 0.2, 0.396, 1  # Fondo azul oscuro
        Rectangle:
            pos: self.pos
            size: self.size
    Label:
        id: popup_title
        text: "Información"
        size_hint: (1, 0.2)
        color: (1, 1, 1, 1)  # Texto blanco
        font_size: 24
        bold: True
    ScrollView:
        size_hint: (1, 0.6)
        GridLayout:
            id: popup_content
            cols: 2
            size_hint_y: None
            height: self.minimum_height
            row_default_height: 30
            row_force_default: True
            spacing: 10
            padding: 10
    Button:
        id: close_button
        text: "Cerrar"
        size_hint: (1, 0.2)
        background_normal: ''
        background_color: (0, 119/255, 194/255, 1)  # Azul claro
        font_size: 20
        bold: True
        height: 50
