<StyledPopup>:
    orientation: 'vertical'
    padding: 20
    spacing: 20
    canvas.before:
        Color:
            rgba: 0.102, 0.2, 0.396, 1  # Fondo azul oscuro
        Rectangle:
            pos: self.pos
            size: self.size
    GridLayout:
        id: popup_content
        cols: 2
        size_hint_y: None
        height: self.minimum_height
        row_default_height: 30
        row_force_default: True
    Button:
        text: "Cerrar"
        size_hint_y: None
        height: 50
        background_normal: ''
        background_color: (0, 119/255, 194/255, 1)  # Azul claro
        on_release: root.controlador.dismiss_popup()