<RecepcionScreen>:
    name: 'recepciones'
    BoxLayout:
        orientation: 'vertical'
        # Formulario
        ScrollView:
            GridLayout:
                cols: 2
                size_hint_y: None
                height: self.minimum_height
                Label:
                    text: 'Nombre:'
                TextInput:
                    id: recepcion_nombre
                TextInput:
                    id: recepcion_id
                Button:
                    text: 'Crear'
                    on_press: root.controlador.crear_recepcion(recepcion_nombre.text)
                Button:
                    text: 'Actualizar'
                    on_press: root.controlador.actualizar_recepcion(recepcion_id.text, recepcion_nombre.text)
                Button:
                    text: 'Eliminar'
                    on_press: root.controlador.eliminar_recepcion(recepcion_id.text)
                Button:
                    text: 'Listar'
                    on_press: root.controlador.listar_recepciones()
        # Lista de recepciones
        ScrollView:
            GridLayout:
                id: lista_recepciones
                cols: 3 # Nombre, Editar, Eliminar
                size_hint_y: None
                height: self.minimum_height
        Button:
            text: 'Volver al Menú'
            on_press: root.manager.current = 'menu'