<SalonesScreen>:
    name: 'salones'
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: 0.102, 0.2, 0.396, 1
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            text: 'Salones de Maranatha Infantil'
            font_size: 30
            color: 1, 1, 1, 1
            size_hint_y: None
            height: 50
        # Formulario
        GridLayout:
            cols: 2
            padding: 20
            spacing: 20
            Label:
                text: 'Id Salón:'
                font_size: 28
                color: 1, 1, 1, 1
                size_hint_y: None
                height: 30
            TextInput:
                id: salon_id
                height: 30
                size_hint_y: None
            Label:
                text: 'Salón:'
                font_size: 28
                color: 1, 1, 1, 1
                size_hint_y: None
                height: 30
            TextInput:
                id: salon_salon
                height: 30
                size_hint_y: None
            Label:
                text: 'Edad:'
                font_size: 28
                color: 1, 1, 1, 1
                size_hint_y: None
                height: 30
            TextInput:
                id: salon_edad
                height: 30
                size_hint_y: None
            Button:
                text: 'Crear'
                font_size: 28
                background_normal: ''
                background_color: (0, 119/255, 194/255, 1)
                size_hint_y: None
                height: 50
                on_press:
                    root.controlador.crear_salon(salon_salon.text, salon_edad.text)
                    salon_salon.text = ''
                    salon_edad.text = ''
            Button:
                text: 'Actualizar'
                font_size: 28
                background_normal: ''
                background_color: (0, 119/255, 194/255, 1)
                size_hint_y: None
                height: 50
                on_press: 
                    root.controlador.actualizar_salon(salon_id.text, salon_salon.text, salon_edad.text)
                    salon_id.text=''
                    salon_salon.text=''
                    salon_edad.text=''
            Button:
                text: 'Eliminar'
                font_size: 28
                background_normal: ''
                background_color: (0, 119/255, 194/255, 1)
                size_hint_y: None
                height: 50
                on_press: 
                    root.controlador.eliminar_salon(salon_id.text)
                    salon_id.text=''
            Button:
                text: "Buscar"
                font_size: 28
                background_normal: ''
                background_color: (0, 119/255, 194/255, 1)
                size_hint_y: None
                height: 50
                on_press:
                    root.controlador.obtener_salon(salon_id.text, salon_salon.text, salon_edad.text)
                    salon_id.text=''
                    salon_salon.text=''
                    salon_edad.text=''
        # Contenedor de Botones
        BoxLayout:
            size_hint_y: None
            height: 50 # Ajusta la altura según sea necesario
            spacing: 10
            padding: 10
            Button:
                text: 'Ver Lista'
                font_size: 28
                background_normal: ''
                background_color: (0, 119/255, 194/255, 1)
                size_hint_y: None
                height: 50
                on_press: root.manager.current = 'lista_salones'
            Button:
                text: 'Gestionar Aulas'
                font_size: 28
                background_normal: ''
                background_color: (0, 119/255, 194/255, 1)
                size_hint_y: None
                height: 50
                on_press: root.manager.current = 'aulas'
            Button:
                text: 'Volver al Menú'
                font_size: 28
                background_normal: ''
                background_color: (0, 119/255, 194/255, 1)
                size_hint_y: None
                height: 50
                on_press: root.manager.current = 'menu'