"""Add docentes, auxiliares and colaboradores

Revision ID: 054d0554adf4
Revises: 3fd8fe7b6f7a
Create Date: 2026-05-16 22:09:24.194817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '054d0554adf4'
down_revision: Union[str, None] = '3fd8fe7b6f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auxiliares',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('numero_equipo', sa.Integer(), nullable=True),
    sa.Column('id_area', sa.Integer(), nullable=True),
    sa.Column('id_capitan', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_area'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['id_capitan'], ['capitanes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('correo')
    )
    with op.batch_alter_table('auxiliares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auxiliares_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auxiliares_sync_id'), ['sync_id'], unique=True)

    op.create_table('colaboradores',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('numero_equipo', sa.Integer(), nullable=True),
    sa.Column('id_area', sa.Integer(), nullable=True),
    sa.Column('id_capitan', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_area'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['id_capitan'], ['capitanes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('correo')
    )
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_colaboradores_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_colaboradores_sync_id'), ['sync_id'], unique=True)

    op.create_table('docentes',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('numero_equipo', sa.Integer(), nullable=True),
    sa.Column('id_area', sa.Integer(), nullable=True),
    sa.Column('id_capitan', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_area'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['id_capitan'], ['capitanes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('correo')
    )
    with op.batch_alter_table('docentes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_docentes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_docentes_sync_id'), ['sync_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docentes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_docentes_sync_id'))
        batch_op.drop_index(batch_op.f('ix_docentes_id'))

    op.drop_table('docentes')
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_colaboradores_sync_id'))
        batch_op.drop_index(batch_op.f('ix_colaboradores_id'))

    op.drop_table('colaboradores')
    with op.batch_alter_table('auxiliares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auxiliares_sync_id'))
        batch_op.drop_index(batch_op.f('ix_auxiliares_id'))

    op.drop_table('auxiliares')
    # ### end Alembic commands ###
