"""Add fecha_nacimiento to servidores

Revision ID: 1c588da2442d
Revises: 14dd872ea690
Create Date: 2026-05-07 00:46:41.991627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c588da2442d'
down_revision: Union[str, None] = '14dd872ea690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servidores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servidores', schema=None) as batch_op:
        batch_op.drop_column('fecha_nacimiento')

    # ### end Alembic commands ###
