"""Add id_area to coordinadores table

Revision ID: 3fd8fe7b6f7a
Revises: 79f5ad79a6ba
Create Date: 2026-05-14 23:39:16.801099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd8fe7b6f7a'
down_revision: Union[str, None] = '79f5ad79a6ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aulas', schema=None) as batch_op:
        batch_op.drop_column('capitan')
        batch_op.drop_column('subcapitan')

    with op.batch_alter_table('coordinadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_area', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'areas', ['id_area'], ['id'])

    with op.batch_alter_table('logisticas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_capitan', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('observaciones', sa.Text(), nullable=True))
        batch_op.alter_column('almacen',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('distribucion',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hidratacion',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('pasillo',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('secretaria',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('capitan',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_logisticas_fecha'), ['fecha'], unique=False)
        batch_op.create_foreign_key(None, 'servidores', ['id_capitan'], ['id'])

    with op.batch_alter_table('servidores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_area', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_capitan', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'areas', ['id_area'], ['id'])
        batch_op.create_foreign_key(None, 'capitanes', ['id_capitan'], ['id'])
        batch_op.drop_column('capitan')
        batch_op.drop_column('area_servicio')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servidores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_servicio', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('capitan', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_capitan')
        batch_op.drop_column('id_area')

    with op.batch_alter_table('logisticas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_logisticas_fecha'))
        batch_op.alter_column('capitan',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('secretaria',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('pasillo',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('hidratacion',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('distribucion',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('almacen',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('observaciones')
        batch_op.drop_column('id_capitan')

    with op.batch_alter_table('coordinadores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_area')

    with op.batch_alter_table('aulas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcapitan', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('capitan', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
