"""Add composite donations support

Revision ID: 49dcd44ce334
Revises: 775fa9d79f0c
Create Date: 2026-04-20 14:37:31.192582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49dcd44ce334'
down_revision: Union[str, None] = '775fa9d79f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donaciones_componentes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('donacion_compuesta_id', sa.Integer(), nullable=False),
    sa.Column('donacion_materia_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_usada', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['donacion_compuesta_id'], ['donaciones.id'], ),
    sa.ForeignKeyConstraint(['donacion_materia_id'], ['donaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('aulas', schema=None) as batch_op:
        batch_op.alter_column('auxiliar', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('capitan', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('colaborador', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('condicion', existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column('maestra', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('ninos', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('ninas', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('subcapitan', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('fecha', existing_type=sa.DATE(), nullable=False)
        batch_op.drop_column('edad')

    with op.batch_alter_table('distribuciones', schema=None) as batch_op:
        batch_op.alter_column('donacion_id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('salon_id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('cantidad', existing_type=sa.FLOAT(), nullable=False)
        batch_op.alter_column('unidad', existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column('fecha', existing_type=sa.DATE(), nullable=False)

    with op.batch_alter_table('donaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_compuesta', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donaciones', schema=None) as batch_op:
        batch_op.drop_column('es_compuesta')

    with op.batch_alter_table('distribuciones', schema=None) as batch_op:
        batch_op.alter_column('fecha', existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column('unidad', existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column('cantidad', existing_type=sa.FLOAT(), nullable=True)
        batch_op.alter_column('salon_id', existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column('donacion_id', existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table('aulas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edad', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('fecha', existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column('subcapitan', existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column('ninas', existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column('ninos', existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column('maestra', existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column('condicion', existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column('colaborador', existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column('capitan', existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column('auxiliar', existing_type=sa.INTEGER(), nullable=True)

    op.drop_table('donaciones_componentes')
    # ### end Alembic commands ###
