"""Remove id_area from hierarchical models

Revision ID: 751a47a06aaa
Revises: ad5a6de3a358
Create Date: 2026-05-18 19:57:18.173726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '751a47a06aaa'
down_revision: Union[str, None] = 'ad5a6de3a358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('areas_area_key'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_areas_area'), ['area'])

    with op.batch_alter_table('aulas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_maestra', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_auxiliar', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_aulas_id_maestra_docentes'), 'docentes', ['id_maestra'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_aulas_id_auxiliar_auxiliares'), 'auxiliares', ['id_auxiliar'], ['id'])
        batch_op.drop_column('auxiliar')
        batch_op.drop_column('colaborador')
        batch_op.drop_column('maestra')

    with op.batch_alter_table('auxiliares', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('auxiliares_cedula_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('auxiliares_correo_key'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_auxiliares_cedula'), ['cedula'])
        batch_op.create_unique_constraint(batch_op.f('uq_auxiliares_correo'), ['correo'])
        batch_op.drop_constraint(batch_op.f('auxiliares_id_area_fkey'), type_='foreignkey')
        batch_op.drop_column('id_area')

    with op.batch_alter_table('capitanes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('capitanes_cedula_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('capitanes_correo_key'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_capitanes_cedula'), ['cedula'])
        batch_op.create_unique_constraint(batch_op.f('uq_capitanes_correo'), ['correo'])

    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('colaboradores_cedula_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('colaboradores_correo_key'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_colaboradores_cedula'), ['cedula'])
        batch_op.create_unique_constraint(batch_op.f('uq_colaboradores_correo'), ['correo'])
        batch_op.drop_constraint(batch_op.f('colaboradores_id_area_fkey'), type_='foreignkey')
        batch_op.drop_column('id_area')

    with op.batch_alter_table('coordinadores', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('coordinadores_cedula_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('coordinadores_correo_key'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_coordinadores_cedula'), ['cedula'])
        batch_op.create_unique_constraint(batch_op.f('uq_coordinadores_correo'), ['correo'])

    with op.batch_alter_table('docentes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('docentes_cedula_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('docentes_correo_key'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_docentes_cedula'), ['cedula'])
        batch_op.create_unique_constraint(batch_op.f('uq_docentes_correo'), ['correo'])
        batch_op.drop_constraint(batch_op.f('docentes_id_area_fkey'), type_='foreignkey')
        batch_op.drop_column('id_area')

    with op.batch_alter_table('lideres', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('lideres_cedula_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('lideres_correo_key'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_lideres_cedula'), ['cedula'])
        batch_op.create_unique_constraint(batch_op.f('uq_lideres_correo'), ['correo'])

    with op.batch_alter_table('salones', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('salones_salon_key'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_salones_salon'), ['salon'])
        batch_op.drop_constraint(batch_op.f('fk_salones_id_area_areas'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_salones_id_area_areas'), 'areas', ['id_area'], ['id'])

    with op.batch_alter_table('servidores', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('servidores_cedula_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('servidores_correo_key'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_servidores_cedula'), ['cedula'])
        batch_op.create_unique_constraint(batch_op.f('uq_servidores_correo'), ['correo'])
        batch_op.drop_constraint(batch_op.f('servidores_id_area_fkey'), type_='foreignkey')
        batch_op.drop_column('id_area')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servidores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_area', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('servidores_id_area_fkey'), 'areas', ['id_area'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_servidores_correo'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_servidores_cedula'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('servidores_correo_key'), ['correo'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('servidores_cedula_key'), ['cedula'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('salones', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_salones_id_area_areas'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_salones_id_area_areas'), 'areas', ['id_area'], ['id'], ondelete='SET NULL')
        batch_op.drop_constraint(batch_op.f('uq_salones_salon'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('salones_salon_key'), ['salon'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('lideres', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_lideres_correo'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_lideres_cedula'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('lideres_correo_key'), ['correo'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('lideres_cedula_key'), ['cedula'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('docentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_area', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('docentes_id_area_fkey'), 'areas', ['id_area'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_docentes_correo'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_docentes_cedula'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('docentes_correo_key'), ['correo'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('docentes_cedula_key'), ['cedula'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('coordinadores', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_coordinadores_correo'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_coordinadores_cedula'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('coordinadores_correo_key'), ['correo'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('coordinadores_cedula_key'), ['cedula'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_area', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('colaboradores_id_area_fkey'), 'areas', ['id_area'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_colaboradores_correo'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_colaboradores_cedula'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('colaboradores_correo_key'), ['correo'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('colaboradores_cedula_key'), ['cedula'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('capitanes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_capitanes_correo'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_capitanes_cedula'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('capitanes_correo_key'), ['correo'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('capitanes_cedula_key'), ['cedula'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('auxiliares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_area', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('auxiliares_id_area_fkey'), 'areas', ['id_area'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_auxiliares_correo'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_auxiliares_cedula'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('auxiliares_correo_key'), ['correo'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('auxiliares_cedula_key'), ['cedula'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('aulas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maestra', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('colaborador', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('auxiliar', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_aulas_id_auxiliar_auxiliares'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_aulas_id_maestra_docentes'), type_='foreignkey')
        batch_op.drop_column('id_auxiliar')
        batch_op.drop_column('id_maestra')

    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_areas_area'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('areas_area_key'), ['area'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
