"""Actualización de modelos areas y salones

Revision ID: 775fa9d79f0c
Revises: c88e4938e80c
Create Date: 2025-04-20 15:45:07.345916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775fa9d79f0c'
down_revision: Union[str, None] = 'c88e4938e80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.alter_column('area',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.create_unique_constraint('uq_areas_area', ['area'])
    
    with op.batch_alter_table('donaciones', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('cantidad',
                   existing_type=sa.FLOAT(),
                   nullable=False)
        batch_op.alter_column('unidad',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('fecha',
                   existing_type=sa.DATE(),
                   nullable=False)
    
    with op.batch_alter_table('salones', schema=None) as batch_op:
        batch_op.alter_column('salon',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('edad',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.create_unique_constraint('uq_salones_salon', ['salon'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salones', type_='unique')
    op.alter_column('salones', 'edad',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('salones', 'salon',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('donaciones', 'fecha',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('donaciones', 'unidad',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('donaciones', 'cantidad',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('donaciones', 'descripcion',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'areas', type_='unique')
    op.alter_column('areas', 'area',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
