"""Creación tablas iniciales

Revision ID: c88e4938e80c
Revises: 
Create Date: 2025-03-21 23:16:46.814547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88e4938e80c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.create_table('donaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.Column('equipo', sa.String(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ensenanzas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capitan', sa.String(), nullable=True),
    sa.Column('subcapitan', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ensenanzas_id'), 'ensenanzas', ['id'], unique=False)
    op.create_table('logisticas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('almacen', sa.Integer(), nullable=True),
    sa.Column('capitan', sa.Integer(), nullable=True),
    sa.Column('distribucion', sa.Integer(), nullable=True),
    sa.Column('hidratacion', sa.Integer(), nullable=True),
    sa.Column('pasillo', sa.Integer(), nullable=True),
    sa.Column('secretaria', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logisticas_id'), 'logisticas', ['id'], unique=False)
    op.create_table('otrasareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alabanza', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('protocolo', sa.Integer(), nullable=True),
    sa.Column('semillitas', sa.Integer(), nullable=True),
    sa.Column('sonido', sa.Integer(), nullable=True),
    sa.Column('teatro', sa.Integer(), nullable=True),
    sa.Column('tv', sa.Integer(), nullable=True),
    sa.Column('ujier', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otrasareas_id'), 'otrasareas', ['id'], unique=False)
    op.create_table('recepciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recepciones_id'), 'recepciones', ['id'], unique=False)
    op.create_table('salones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon', sa.String(), nullable=True),
    sa.Column('edad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salones_id'), 'salones', ['id'], unique=False)
    op.create_table('aulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auxiliar', sa.Integer(), nullable=True),
    sa.Column('capitan', sa.Integer(), nullable=True),
    sa.Column('colaborador', sa.Integer(), nullable=True),
    sa.Column('condicion', sa.String(), nullable=True),
    sa.Column('edad', sa.String(), nullable=True),
    sa.Column('maestra', sa.Integer(), nullable=True),
    sa.Column('ninos', sa.Integer(), nullable=True),
    sa.Column('ninas', sa.Integer(), nullable=True),
    sa.Column('subcapitan', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('id_salon', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_salon'], ['salones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aulas_id'), 'aulas', ['id'], unique=False)
    op.create_table('distribuciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donacion_id', sa.Integer(), nullable=True),
    sa.Column('salon_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['donacion_id'], ['donaciones.id'], ),
    sa.ForeignKeyConstraint(['salon_id'], ['salones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distribuciones')
    op.drop_index(op.f('ix_aulas_id'), table_name='aulas')
    op.drop_table('aulas')
    op.drop_index(op.f('ix_salones_id'), table_name='salones')
    op.drop_table('salones')
    op.drop_index(op.f('ix_recepciones_id'), table_name='recepciones')
    op.drop_table('recepciones')
    op.drop_index(op.f('ix_otrasareas_id'), table_name='otrasareas')
    op.drop_table('otrasareas')
    op.drop_index(op.f('ix_logisticas_id'), table_name='logisticas')
    op.drop_table('logisticas')
    op.drop_index(op.f('ix_ensenanzas_id'), table_name='ensenanzas')
    op.drop_table('ensenanzas')
    op.drop_table('donaciones')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
