"""add levantado column to jerarquia tables

Revision ID: d26ccbc5537c
Revises: d832ef8de7d5
Create Date: 2026-06-26 17:37:51.532138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26ccbc5537c'
down_revision: Union[str, None] = 'd832ef8de7d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auxiliares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('levantado', sa.String(length=5), nullable=True))

    with op.batch_alter_table('capitanes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('levantado', sa.String(length=5), nullable=True))

    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('levantado', sa.String(length=5), nullable=True))

    with op.batch_alter_table('coordinadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('levantado', sa.String(length=5), nullable=True))

    with op.batch_alter_table('docentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('levantado', sa.String(length=5), nullable=True))

    with op.batch_alter_table('servidores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('levantado', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servidores', schema=None) as batch_op:
        batch_op.drop_column('levantado')

    with op.batch_alter_table('docentes', schema=None) as batch_op:
        batch_op.drop_column('levantado')

    with op.batch_alter_table('coordinadores', schema=None) as batch_op:
        batch_op.drop_column('levantado')

    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.drop_column('levantado')

    with op.batch_alter_table('capitanes', schema=None) as batch_op:
        batch_op.drop_column('levantado')

    with op.batch_alter_table('auxiliares', schema=None) as batch_op:
        batch_op.drop_column('levantado')

    # ### end Alembic commands ###
