"""Add last_sync and security columns

Revision ID: e021da1f58d8
Revises: 7d46174d3e47
Create Date: 2026-05-03 18:28:51.527766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e021da1f58d8'
down_revision: Union[str, None] = '7d46174d3e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alimentos_preparados', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('alimentos_preparados', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('alimentos_preparados', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_alimentos_preparados_id'), 'alimentos_preparados', ['id'], unique=False)
    op.add_column('alimentos_preparados_componentes', sa.Column('last_sync', sa.DateTime(), nullable=True))
    op.alter_column('alimentos_preparados_componentes', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('alimentos_preparados_componentes', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('alimentos_preparados_componentes', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_alimentos_preparados_componentes_id'), 'alimentos_preparados_componentes', ['id'], unique=False)
    op.alter_column('areas', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('areas', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('areas', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('aulas', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('aulas', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('aulas', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('distribuciones', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('distribuciones', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('distribuciones', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_distribuciones_id'), 'distribuciones', ['id'], unique=False)
    op.alter_column('donaciones', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('donaciones', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('donaciones', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_donaciones_id'), 'donaciones', ['id'], unique=False)
    op.add_column('ensenanzas', sa.Column('last_sync', sa.DateTime(), nullable=True))
    op.alter_column('ensenanzas', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ensenanzas', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('ensenanzas', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.add_column('logisticas', sa.Column('last_sync', sa.DateTime(), nullable=True))
    op.alter_column('logisticas', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('logisticas', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('logisticas', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_logisticas_id'), 'logisticas', ['id'], unique=False)
    op.alter_column('otrasareas', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('otrasareas', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('otrasareas', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.add_column('permissions', sa.Column('last_sync', sa.DateTime(), nullable=True))
    op.alter_column('permissions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('permissions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('permissions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.alter_column('recepciones', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('recepciones', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('recepciones', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('roles', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('roles', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('roles', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.alter_column('salones', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('salones', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('salones', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.add_column('sync_queue', sa.Column('last_sync', sa.DateTime(), nullable=True))
    op.alter_column('sync_queue', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sync_queue', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('sync_queue', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_sync_queue_id'), 'sync_queue', ['id'], unique=False)
    op.alter_column('usuarios', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('usuarios', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('usuarios', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.alter_column('usuarios', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('usuarios', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('usuarios', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_sync_queue_id'), table_name='sync_queue')
    op.alter_column('sync_queue', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('sync_queue', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('sync_queue', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('sync_queue', 'last_sync')
    op.alter_column('salones', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('salones', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('salones', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.alter_column('roles', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('roles', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('roles', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('recepciones', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('recepciones', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('recepciones', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.alter_column('permissions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('permissions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('permissions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('permissions', 'last_sync')
    op.alter_column('otrasareas', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('otrasareas', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('otrasareas', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_logisticas_id'), table_name='logisticas')
    op.alter_column('logisticas', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('logisticas', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('logisticas', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('logisticas', 'last_sync')
    op.alter_column('ensenanzas', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('ensenanzas', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('ensenanzas', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('ensenanzas', 'last_sync')
    op.drop_index(op.f('ix_donaciones_id'), table_name='donaciones')
    op.alter_column('donaciones', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('donaciones', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('donaciones', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_distribuciones_id'), table_name='distribuciones')
    op.alter_column('distribuciones', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('distribuciones', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('distribuciones', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('aulas', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('aulas', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('aulas', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('areas', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('areas', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('areas', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_alimentos_preparados_componentes_id'), table_name='alimentos_preparados_componentes')
    op.alter_column('alimentos_preparados_componentes', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('alimentos_preparados_componentes', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('alimentos_preparados_componentes', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('alimentos_preparados_componentes', 'last_sync')
    op.drop_index(op.f('ix_alimentos_preparados_id'), table_name='alimentos_preparados')
    op.alter_column('alimentos_preparados', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('alimentos_preparados', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('alimentos_preparados', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
