"""add_direccion_to_jerarquia_tables

Revision ID: f69f771276c5
Revises: d26ccbc5537c
Create Date: 2026-06-26 18:13:19.013027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f69f771276c5'
down_revision: Union[str, None] = 'd26ccbc5537c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auxiliares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=1000), nullable=True))

    with op.batch_alter_table('capitanes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=1000), nullable=True))

    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=1000), nullable=True))

    with op.batch_alter_table('coordinadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=1000), nullable=True))

    with op.batch_alter_table('docentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=1000), nullable=True))

    with op.batch_alter_table('servidores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servidores', schema=None) as batch_op:
        batch_op.drop_column('direccion')

    with op.batch_alter_table('docentes', schema=None) as batch_op:
        batch_op.drop_column('direccion')

    with op.batch_alter_table('coordinadores', schema=None) as batch_op:
        batch_op.drop_column('direccion')

    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.drop_column('direccion')

    with op.batch_alter_table('capitanes', schema=None) as batch_op:
        batch_op.drop_column('direccion')

    with op.batch_alter_table('auxiliares', schema=None) as batch_op:
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###
