from .areas_screen import AreasScreen
from .aulas_screen import AulasScreen
from .ayuda_screen import AyudaScreen
from .distribuciones_screen import DistribucionesScreen
from .donaciones_screen import DonacionesScreen
from .ensenanza_screen import EnsenanzaScreen
from .estadistica_screen import EstadistaScreen
from .logistica_Screen import LogisticaScreen
from .menu_screen import MenuScreen
from .otrasareas_screen import OtrasAreasScreen
from .recepcion_screen import RecepcionScreen
from .reporte_screen import ReporteScreen
from .salones_screen import SalonesScreen